# Spring boot application
spring:
  application:
    name: itcast-haoke-manage-api-server
  profiles:
    active: aliyun
server:
  port: 18080

#logging.level.root=DEBUG

# 应用名称
dubbo:
  application:
    name: dubbo-consumer-haoke-manage
  # zk注册中心
  registry:
    address: zookeeper://192.168.244.128:2181
    client: zkclient


